"""
Performance test script generation tool.
Generates locust or k6 load-testing scripts from API specifications.
"""

import json
from agent.tool_registry import tool
from tools import parse_json_arg


@tool(
    name="generate_perf_test",
    description="Generate performance/load test scripts (locust or k6) from API endpoint descriptions. Produces ready-to-run code with realistic user scenarios.",
    parameters={
        "type": "object",
        "properties": {
            "api_spec_json": {
                "type": "string",
                "description": "JSON array of API endpoint definitions. Each endpoint: method (GET/POST/PUT), path, description, payload (example request body), headers"
            },
            "framework": {
                "type": "string",
                "enum": ["locust", "k6"],
                "description": "Load testing framework: locust (Python) or k6 (JavaScript)"
            },
            "target_host": {
                "type": "string",
                "description": "Target host URL (e.g. https://api.example.com)"
            },
            "scenario": {
                "type": "string",
                "enum": ["smoke", "load", "stress", "soak"],
                "description": "Test scenario type: smoke (5-10 users), load (ramp 50-200), stress (ramp to break point), soak (steady 100 users, long duration)"
            },
        },
        "required": ["api_spec_json", "target_host"],
    }
)
def generate_perf_test(
    api_spec_json: str,
    framework: str = "locust",
    target_host: str = "http://localhost",
    scenario: str = "load",
) -> str:
    try:
        endpoints = parse_json_arg(api_spec_json)
    except json.JSONDecodeError as e:
        return f"Error parsing API spec: {e}"

    if not isinstance(endpoints, list):
        endpoints = [endpoints]

    if framework == "locust":
        script = _gen_locust(endpoints, target_host, scenario)
    elif framework == "k6":
        script = _gen_k6(endpoints, target_host, scenario)
    else:
        return f"Unknown framework: {framework}"

    return json.dumps({
        "framework": framework,
        "scenario": scenario,
        "target_host": target_host,
        "endpoint_count": len(endpoints),
        "script": script,
        "instructions": {
            "locust": "pip install locust; locust -f script.py --host=TARGET",
            "k6": "Install k6: brew install k6; k6 run script.js",
        }.get(framework, ""),
    }, ensure_ascii=False, indent=2)


def _scenario_config(scenario: str, framework: str):
    configs = {
        "smoke": {"users": 10, "spawn_rate": 2, "duration": "2m", "desc": "Smoke test: verify system works under minimal load"},
        "load": {"users": 100, "spawn_rate": 10, "duration": "10m", "desc": "Load test: ramp up to typical peak and sustain"},
        "stress": {"users": 500, "spawn_rate": 50, "duration": "15m", "desc": "Stress test: find the breaking point"},
        "soak": {"users": 100, "spawn_rate": 5, "duration": "30m", "desc": "Soak test: sustained load over long period"},
    }
    return configs.get(scenario, configs["load"])


def _gen_locust(endpoints: list, target_host: str, scenario: str) -> str:
    config = _scenario_config(scenario, "locust")

    lines = [
        f"\"\"\"Locust load test - auto-generated by AI.\"\"\"",
        f"# Scenario: {config['desc']}",
        f"# Target: {target_host}",
        f"# Users: {config['users']}, Rate: {config['spawn_rate']}/s, Duration: {config['duration']}",
        "",
        "from locust import HttpUser, task, between, events",
        "import random",
        "import json",
        "",
        "",
    ]

    # Generate request bodies as module-level constants
    for i, ep in enumerate(endpoints):
        payload = ep.get("payload", {})
        if payload and isinstance(payload, dict):
            var_name = f"PAYLOAD_{i}"
            lines.append(f"{var_name} = {json.dumps(payload, ensure_ascii=False)}")

    lines.extend([
        "",
        f"class APIUser(HttpUser):",
        f"    host = {json.dumps(target_host)}",
        f"    wait_time = between(1, 3)  # 1-3 seconds between tasks",
        "",
    ])

    # Generate @task methods
    for i, ep in enumerate(endpoints):
        method = ep.get("method", "GET").upper()
        path = ep.get("path", "/")
        desc = ep.get("description", "")

        lines.append(f"    @task")
        lines.append(f"    def {method.lower()}_{i}(self):")

        payload = ep.get("payload", {})
        if method == "GET":
            lines.append(f"        self.client.get({json.dumps(path)}, name={json.dumps(desc[:50])})")
        elif method == "POST":
            if payload:
                lines.append(f"        self.client.post({json.dumps(path)}, json=PAYLOAD_{i}, name={json.dumps(desc[:50])})")
            else:
                lines.append(f"        self.client.post({json.dumps(path)}, json={{}}, name={json.dumps(desc[:50])})")
        elif method == "PUT":
            if payload:
                lines.append(f"        self.client.put({json.dumps(path)}, json=PAYLOAD_{i}, name={json.dumps(desc[:50])})")
            else:
                lines.append(f"        self.client.put({json.dumps(path)}, json={{}}, name={json.dumps(desc[:50])})")
        elif method == "DELETE":
            lines.append(f"        self.client.delete({json.dumps(path)}, name={json.dumps(desc[:50])})")

        lines.append("")

    # Add lifecycle hooks
    lines.extend([
        f"    def on_start(self):",
        f"        # Called when a simulated user starts",
        f"        self.client.get('/')",
    ])

    return "\n".join(lines)


def _gen_k6(endpoints: list, target_host: str, scenario: str) -> str:
    config = _scenario_config(scenario, "k6")

    lines = [
        f"// k6 load test - auto-generated by AI",
        f"// Scenario: {config['desc']}",
        f"// Target: {target_host}",
        f"// Users: {config['users']}, Rate: {config['spawn_rate']}/s, Duration: {config['duration']}",
        "",
        "import http from 'k6/http';",
        "import { sleep, check } from 'k6';",
        "import { Rate, Trend } from 'k6/metrics';",
        "",
        "const errorRate = new Rate('errors');",
        "const responseTime = new Trend('response_time');",
        "",
        "export const options = {",
        f"  stages: [",
        f"    {{ duration: '1m', target: {config['users'] // 3} }},",
        f"    {{ duration: '{config['duration'][:-1]}m', target: {config['users']} }},",
        f"    {{ duration: '1m', target: 0 }},",
        f"  ],",
        f"  thresholds: {{",
        f"    http_req_duration: ['p(95)<2000'],  // 95% of requests < 2s",
        f"    errors: ['rate<0.1'],               // error rate < 10%",
        f"  }},",
        "};",
        "",
        f"const BASE_URL = '{target_host}';",
        "",
    ]

    # Payloads as module-level consts
    for i, ep in enumerate(endpoints):
        payload = ep.get("payload", {})
        if payload and isinstance(payload, dict):
            lines.append(f"const PAYLOAD_{i} = {json.dumps(payload)};")

    lines.extend([
        "",
        "export default function() {",
    ])

    for i, ep in enumerate(endpoints):
        method = ep.get("method", "GET").lower()
        path = ep.get("path", "/")
        desc = ep.get("description", "")

        payload = ep.get("payload", {})
        if method == "get":
            lines.append(f"  // {desc}")
            lines.append(f"  let res{i} = http.get(BASE_URL + {json.dumps(path)});")
        elif method == "post":
            body = f"PAYLOAD_{i}" if payload else "{}"
            lines.append(f"  let res{i} = http.post(BASE_URL + {json.dumps(path)}, {body});")
        elif method in ("put", "patch"):
            body = f"PAYLOAD_{i}" if payload else "{}"
            lines.append(f"  let res{i} = http.{method}(BASE_URL + {json.dumps(path)}, {body});")
        elif method == "delete":
            lines.append(f"  let res{i} = http.del(BASE_URL + {json.dumps(path)});")

        lines.append(f"  check(res{i}, {{")
        lines.append(f"    '{method.upper()} {path} - status is 200': (r) => r.status === 200,")
        lines.append(f"  }});")
        lines.append(f"  errorRate.add(res{i}.status !== 200);")
        lines.append(f"  responseTime.add(res{i}.timings.duration);")
        lines.append(f"  sleep(1);")
        lines.append("")

    lines.append("}")

    return "\n".join(lines)
