"""
UI test script generation tool.
Generates Selenium WebDriver or Playwright test scripts from test case descriptions.
Agent generates the code, user can execute with run_script tool.
"""

import json
from agent.tool_registry import tool
from tools import parse_json_arg


@tool(
    name="generate_ui_test",
    description="Generate UI automation test scripts (Selenium/Playwright) from test case descriptions. Produces runnable Python code that can be executed via run_script tool.",
    parameters={
        "type": "object",
        "properties": {
            "test_cases_json": {
                "type": "string",
                "description": "JSON array of test case objects. Each should have: title, steps (with action/selector/input), expectedResult, url (base URL)"
            },
            "framework": {
                "type": "string",
                "enum": ["selenium", "playwright"],
                "description": "UI automation framework to generate code for"
            },
            "base_url": {
                "type": "string",
                "description": "Base URL of the application under test (e.g. https://example.com)"
            },
            "headless": {
                "type": "boolean",
                "description": "Run browser in headless mode (default true)"
            },
        },
        "required": ["test_cases_json"],
    }
)
def generate_ui_test(
    test_cases_json: str,
    framework: str = "selenium",
    base_url: str = "http://localhost",
    headless: bool = True,
) -> str:
    try:
        cases = parse_json_arg(test_cases_json)
    except json.JSONDecodeError as e:
        return f"Error parsing test cases: {e}"

    if not isinstance(cases, list):
        cases = [cases]

    if framework == "selenium":
        script = _gen_selenium(cases, base_url, headless)
    elif framework == "playwright":
        script = _gen_playwright(cases, base_url, headless)
    else:
        return f"Unknown framework: {framework}"

    return json.dumps({
        "framework": framework,
        "base_url": base_url,
        "test_count": len(cases),
        "script": script,
        "instructions": {
            "selenium": "pip install selenium; ensure chromedriver is in PATH",
            "playwright": "pip install playwright; playwright install chromium",
        }.get(framework, ""),
        "usage": f"Save the script to a .py file and run: python script.py\nOr execute with run_script tool.",
    }, ensure_ascii=False, indent=2)


def _gen_selenium(cases: list, base_url: str, headless: bool) -> str:
    lines = [
        "\"\"\"Selenium WebDriver UI tests - auto-generated by AI.\"\"\"",
        "import time",
        "from selenium import webdriver",
        "from selenium.webdriver.common.by import By",
        "from selenium.webdriver.common.keys import Keys",
        "from selenium.webdriver.support.ui import WebDriverWait",
        "from selenium.webdriver.support import expected_conditions as EC",
        "from selenium.common.exceptions import TimeoutException, NoSuchElementException",
        "",
        "",
        "options = webdriver.ChromeOptions()",
    ]

    if headless:
        lines.append("options.add_argument('--headless=new')")

    lines.extend([
        "options.add_argument('--no-sandbox')",
        "options.add_argument('--disable-dev-shm-usage')",
        "driver = webdriver.Chrome(options=options)",
        "driver.implicitly_wait(5)",
        "wait = WebDriverWait(driver, 10)",
        f"BASE_URL = {base_url!r}",
        "",
        "passed = 0",
        "failed = 0",
        "",
    ])

    for tc in cases:
        tid = tc.get("id", "TC-??").replace("-", "_")
        title = tc.get("title", "test case")
        url_path = tc.get("module", "") or ""

        lines.append(f"# {title}")
        lines.append(f"def test_{tid}():")
        lines.append("    global passed, failed")
        lines.append("    try:")
        lines.append(f"        driver.get(BASE_URL + {json.dumps(url_path)})")
        lines.append("        time.sleep(1)")

        for step in tc.get("steps", []):
            action = step.get("action", "")
            data = step.get("data", "")
            expected = step.get("expected", "")
            selector = step.get("selector", "")

            lines.append(f"        # {action}")
            if selector and data:
                lines.append(f"        el = driver.find_element(By.CSS_SELECTOR, {json.dumps(selector)})")
                lines.append(f"        el.send_keys({json.dumps(data)})")
            elif selector and "click" in action.lower():
                lines.append(f"        driver.find_element(By.CSS_SELECTOR, {json.dumps(selector)}).click()")
            elif selector:
                lines.append(f"        el = driver.find_element(By.CSS_SELECTOR, {json.dumps(selector)})")

            if expected:
                lines.append(f"        # Expected: {expected[:100]}")

        lines.append("        print(f'  PASS: {title}')")
        lines.append("        passed += 1")
        lines.append("    except Exception as e:")
        lines.append("        print(f'  FAIL: {title} - {e}')")
        lines.append("        failed += 1")
        lines.append("")

    # Build test function list for the runner
    test_funcs = []
    for tc in cases:
        tid = tc.get("id", "TC-??").replace("-", "_")
        test_funcs.append("test_" + tid)

    lines.append("")
    lines.append("# Run all tests")
    lines.append("tests = [" + ", ".join(test_funcs) + "]")
    lines.append("for test in tests:")
    lines.append("    test()")
    lines.append("    time.sleep(0.5)")
    lines.append("")
    lines.append("print(f'\\n=== Results: {passed} passed, {failed} failed ===')")
    lines.append("driver.quit()")

    return "\n".join(lines)


def _gen_playwright(cases: list, base_url: str, headless: bool) -> str:
    lines = [
        "\"\"\"Playwright UI tests - auto-generated by AI.\"\"\"",
        "import asyncio",
        "from playwright.async_api import async_playwright",
        "",
        "",
        "async def run_tests():",
        f"    base_url = {base_url!r}",
    ]
    if headless:
        lines.append("    async with async_playwright() as p:")
        lines.append("        browser = await p.chromium.launch(headless=True)")
    else:
        lines.append("    async with async_playwright() as p:")
        lines.append("        browser = await p.chromium.launch(headless=False, slow_mo=100)")

    lines.extend([
        "        page = await browser.new_page()",
        "        passed = 0",
        "        failed = 0",
        "",
    ])

    for tc in cases:
        tid = tc.get("id", "TC-??").replace("-", "_")
        title = tc.get("title", "test case")
        url_path = tc.get("module", "") or ""

        lines.append(f"        # {title}")
        lines.append(f"        try:")
        lines.append(f"            await page.goto(base_url + {json.dumps(url_path)})")

        for step in tc.get("steps", []):
            action = step.get("action", "")
            data = step.get("data", "")
            selector = step.get("selector", "")

            lines.append(f"            # {action}")
            if selector and data:
                lines.append(f"            await page.fill({json.dumps(selector)}, {json.dumps(data)})")
            elif selector and "click" in action.lower():
                lines.append(f"            await page.click({json.dumps(selector)})")

        lines.append(f"            print(f'  PASS: {title}')")
        lines.append(f"            passed += 1")
        lines.append(f"        except Exception as e:")
        lines.append(f"            print(f'  FAIL: {title} - {{e}}')")
        lines.append(f"            failed += 1")
        lines.append("")

    lines.extend([
        "        print(f'\\n=== Results: {passed} passed, {failed} failed ===')",
        "        await browser.close()",
        "",
        "asyncio.run(run_tests())",
    ])

    return "\n".join(lines)
