import type { IndexedDbTransactionScope } from '@/capabilities/database/adapters/indexeddb/IndexedDbUnitOfWork';
import { TutorIndexedDb, TutorIndexedDbStore } from '@/capabilities/database/adapters/indexeddb/TutorIndexedDb';
import type { TransactionContext } from '@/capabilities/database/public';
import type { AgentRunId, InstantMs } from '@/kernel/public';
import type { AgentInvocationRecord, AgentRunAggregate, AgentRunClaimOptions, AgentRunEventRecord, AgentRunRecord, AgentRunRecoveryOptions, AgentRunRepository } from '../contracts/AgentRunRepository';

interface StoredRun extends AgentRunAggregate { readonly runId: string; readonly idempotencyKey: string; readonly invocations: readonly AgentInvocationRecord[]; }

export class IndexedDbAgentRunRepository implements AgentRunRepository {
  constructor(private readonly database: TutorIndexedDb, private readonly scope: IndexedDbTransactionScope) {}
  async create(run: AgentRunRecord, created: AgentRunEventRecord, context: TransactionContext): Promise<void> {
    if (await this.findByIdempotencyKey(run.idempotencyKey)) throw new Error(`Agent run already exists: ${run.idempotencyKey}`);
    this.scope.stage(context, { type:'add', store:TutorIndexedDbStore.AgentRunAggregates, value:stored(run,[created],[]) });
  }
  async replace(run: AgentRunRecord, expectedVersion: number, event: AgentRunEventRecord, context: TransactionContext): Promise<void> {
    const current=await this.findById(run.id); if(!current||current.run.version!==expectedVersion||run.version!==expectedVersion+1) throw new Error(`Agent run version conflict: ${run.id}`);
    this.scope.stage(context,{type:'put',store:TutorIndexedDbStore.AgentRunAggregates,value:stored(run,[...current.events,event],(await this.get(run.id))!.invocations)});
  }
  async findById(id: AgentRunId): Promise<AgentRunAggregate|undefined> { const item=await this.get(id); return item&&{run:item.run,events:item.events}; }
  async findByIdempotencyKey(key:string): Promise<AgentRunAggregate|undefined> { const all=await this.database.getAll<StoredRun>(TutorIndexedDbStore.AgentRunAggregates); const item=all.find(v=>v.idempotencyKey===key); return item&&{run:item.run,events:item.events}; }
  async appendInvocation(invocation:AgentInvocationRecord, context:TransactionContext):Promise<void> { const current=await this.get(invocation.agentRunId); if(!current) throw new Error(`Agent run not found: ${invocation.agentRunId}`); this.scope.stage(context,{type:'put',store:TutorIndexedDbStore.AgentRunAggregates,value:stored(current.run,current.events,[...current.invocations,invocation])}); }
  async updateInvocationResult(id:AgentInvocationRecord['id'], value:Pick<AgentInvocationRecord,'providerRequestId'|'inputTokens'|'outputTokens'|'latencyMs'|'finishReason'>, context:TransactionContext):Promise<void>{const current=await this.findInvocation(id);if(!current||current.invocation.validationStatus!=='pending')throw new Error(`Agent invocation result conflict: ${id}`);this.scope.stage(context,{type:'put',store:TutorIndexedDbStore.AgentRunAggregates,value:stored(current.stored.run,current.stored.events,current.stored.invocations.map(item=>item.id===id?{...item,...value}:item))});}
  async updateInvocationValidation(id:AgentInvocationRecord['id'], status:AgentInvocationRecord['validationStatus'], errorCode:string|undefined, context:TransactionContext):Promise<void>{const current=await this.findInvocation(id);if(!current||current.invocation.validationStatus!=='pending')throw new Error(`Agent invocation validation conflict: ${id}`);this.scope.stage(context,{type:'put',store:TutorIndexedDbStore.AgentRunAggregates,value:stored(current.stored.run,current.stored.events,current.stored.invocations.map(item=>item.id===id?{...item,validationStatus:status,errorCode}:item))});}
  async listInvocations(id:AgentRunId):Promise<readonly AgentInvocationRecord[]> { return (await this.get(id))?.invocations??[]; }
  async listRecent(limit:number):Promise<readonly AgentRunAggregate[]> { if(!Number.isInteger(limit)||limit<1||limit>50)throw new RangeError('Agent recent limit must be between 1 and 50'); const all=await this.database.getAll<StoredRun>(TutorIndexedDbStore.AgentRunAggregates); return [...all].sort((a,b)=>b.run.updatedAt-a.run.updatedAt||String(b.run.id).localeCompare(String(a.run.id))).slice(0,limit).map(v=>({run:v.run,events:v.events})); }
  async listRunnable(now:InstantMs,limit:number):Promise<readonly AgentRunAggregate[]> { if(!Number.isInteger(limit)||limit<1||limit>3)throw new RangeError('Agent runnable limit must be between 1 and 3'); const all=await this.database.getAll<StoredRun>(TutorIndexedDbStore.AgentRunAggregates); return all.filter(v=>v.run.status==='queued'&&(!v.run.nextRunAt||v.run.nextRunAt<=now)).sort((a,b)=>a.run.updatedAt-b.run.updatedAt).slice(0,limit).map(v=>({run:v.run,events:v.events})); }
  async claimRunnable(options:AgentRunClaimOptions):Promise<readonly AgentRunAggregate[]> {
    if(!options.workerId.trim()||!Number.isInteger(options.limit)||options.limit<1||options.limit>3||options.eventIds.length<options.limit)throw new Error('Invalid agent run claim options');
    return this.database.mutateStore<StoredRun,readonly AgentRunAggregate[]>(TutorIndexedDbStore.AgentRunAggregates,(values)=>{
      const candidates=values.filter(v=>v.run.status==='queued'&&(!v.run.nextRunAt||v.run.nextRunAt<=options.now)).sort((a,b)=>a.run.updatedAt-b.run.updatedAt).slice(0,options.limit);
      const operations=[]; const claimed=[];
      for(let index=0;index<candidates.length;index+=1){const item=candidates[index];const run={...item.run,status:'running' as const,attemptCount:item.run.attemptCount+1,leaseOwner:options.workerId.trim(),leaseExpiresAt:options.leaseExpiresAt,updatedAt:options.now,version:item.run.version+1};const event={id:options.eventIds[index],agentRunId:run.id,eventType:'started' as const,fromStatus:'queued' as const,toStatus:'running' as const,reasonCode:'agent_run.claimed',payload:{workerId:options.workerId.trim(),leaseExpiresAt:options.leaseExpiresAt},occurredAt:options.now,idempotencyKey:`agent-run:${run.id}:claim:${run.version}`};const next=stored(run,[...item.events,event],item.invocations);operations.push({type:'put' as const,store:TutorIndexedDbStore.AgentRunAggregates,value:next});claimed.push({run,events:[...item.events,event]});}
      return {operations,result:claimed};
    });
  }
  async recoverExpiredLeases(options:AgentRunRecoveryOptions):Promise<readonly AgentRunAggregate[]> {if(!Number.isInteger(options.limit)||options.limit<1||options.limit>100||options.eventIds.length<options.limit)throw new Error('Invalid agent run recovery options');return this.database.mutateStore<StoredRun,readonly AgentRunAggregate[]>(TutorIndexedDbStore.AgentRunAggregates,(values)=>{const candidates=values.filter(v=>v.run.status==='running'&&v.run.leaseExpiresAt!==undefined&&v.run.leaseExpiresAt<=options.now).sort((a,b)=>(a.run.leaseExpiresAt??0)-(b.run.leaseExpiresAt??0)).slice(0,options.limit);const operations=[];const recovered=[];for(let index=0;index<candidates.length;index+=1){const item=candidates[index];const run={...item.run,status:'queued' as const,nextRunAt:options.now,leaseOwner:undefined,leaseExpiresAt:undefined,updatedAt:options.now,version:item.run.version+1};const event={id:options.eventIds[index],agentRunId:run.id,eventType:'recovered' as const,fromStatus:'running' as const,toStatus:'queued' as const,reasonCode:'agent_run.lease_expired',payload:{},occurredAt:options.now,idempotencyKey:`agent-run:${run.id}:recover:${run.version}`};operations.push({type:'put' as const,store:TutorIndexedDbStore.AgentRunAggregates,value:stored(run,[...item.events,event],item.invocations)});recovered.push({run,events:[...item.events,event]});}return{operations,result:recovered};});}
  private get(id:AgentRunId):Promise<StoredRun|undefined>{ return this.database.get<StoredRun>(TutorIndexedDbStore.AgentRunAggregates,id); }
  private async findInvocation(id:AgentInvocationRecord['id']):Promise<{stored:StoredRun;invocation:AgentInvocationRecord}|undefined>{const all=await this.database.getAll<StoredRun>(TutorIndexedDbStore.AgentRunAggregates);for(const stored of all){const invocation=stored.invocations.find(item=>item.id===id);if(invocation)return{stored,invocation};}return undefined;}
}
function stored(run:AgentRunRecord,events:readonly AgentRunEventRecord[],invocations:readonly AgentInvocationRecord[]):StoredRun{return{runId:run.id,idempotencyKey:run.idempotencyKey,run,events,invocations};}
