import type { JsonObject } from '@/kernel/public';

export interface PracticeGenerationShard {
  readonly index: number;
  readonly offset: number;
  readonly count: number;
}

export interface PracticeGenerationPlan {
  readonly totalCount: number;
  readonly shardConcurrency: number;
  readonly shards: readonly PracticeGenerationShard[];
}

// A single structured response becomes output-token bound well before twelve
// questions. Keep the one-call path for genuinely small drills and shard every
// larger set so provider decoding happens in parallel.
const LARGE_BATCH_THRESHOLD = 5;
const DEFAULT_SHARD_SIZE = 5;
const COMPLEX_SHARD_SIZE = 4;
const GRAPHICAL_SHARD_SIZE = 3;
// Large batches use short independent provider calls. This is separate from
// the user's Agent task concurrency and remains bounded by the global gate.
const DEFAULT_SHARD_CONCURRENCY = 6;
const COMPLEX_SHARD_CONCURRENCY = 4;

export function coreGenerationTokenBudget(questionCount: number, capabilityCode = ''): number {
  const base = Math.max(2_600, 1_400 + Math.max(1, questionCount) * 480);
  const structuralAllowance = isComplexVisualStructure(capabilityCode) ? 1_400 : 0;
  return Math.min(5_800, base + structuralAllowance);
}

export function lectureGenerationTokenBudget(capabilityCode = ''): number {
  return isComplexVisualStructure(capabilityCode) ? 3_200 : 2_600;
}

export function questionShardTokenBudget(questionCount: number, capabilityCode = ''): number {
  const base = 800 + Math.max(1, questionCount) * 320;
  const structuralAllowance = isComplexVisualStructure(capabilityCode) ? 1_500 : 0;
  return Math.min(5_000, Math.max(1_800, base + structuralAllowance));
}

export function createPracticeGenerationPlan(
  questionCount: number,
  capabilityCode = ''
): PracticeGenerationPlan {
  const totalCount = Math.max(1, Math.floor(questionCount));
  const graphical = isGraphicalGenerationCapability(capabilityCode);
  if (totalCount <= LARGE_BATCH_THRESHOLD && !(graphical && totalCount > GRAPHICAL_SHARD_SIZE)) {
    return {
      totalCount,
      // Three- and four-question tutor drills are the latency-sensitive path.
      // The caller may split lecture/questions into one provider wave while
      // one-, two- and five-question compatibility flows retain one response.
      shardConcurrency: totalCount >= 3 && totalCount <= 4 ? 2 : 1,
      shards: [{ index: 0, offset: 0, count: totalCount }]
    };
  }
  const complex = isComplexVisualStructure(capabilityCode);
  const shardSize = graphical
    ? GRAPHICAL_SHARD_SIZE
    : complex
      ? COMPLEX_SHARD_SIZE
      : DEFAULT_SHARD_SIZE;
  const shards: PracticeGenerationShard[] = [];
  for (let offset = 0, index = 0; offset < totalCount; offset += shardSize, index += 1) {
    shards.push({
      index,
      offset,
      count: Math.min(shardSize, totalCount - offset)
    });
  }
  return {
    totalCount,
    shardConcurrency: complex ? COMPLEX_SHARD_CONCURRENCY : DEFAULT_SHARD_CONCURRENCY,
    shards
  };
}

/**
 * Graphical questions carry several independent SVG documents per question.
 * They can publish a smaller valid subset without exposing malformed questions.
 * Other capabilities retain the established 80% boundary.
 */
export function practiceQuestionAcceptanceRatio(capabilityCode = ''): number {
  return isGraphicalGenerationCapability(capabilityCode) ? 0.6 : 0.8;
}

export function isGraphicalGenerationCapability(capabilityCode: string): boolean {
  return capabilityCode === 'aptitude.judgment.graphical'
    || capabilityCode.startsWith('aptitude.judgment.graphical.');
}

export function shouldGeneratePracticeBlocksInParallel(
  plan: PracticeGenerationPlan
): boolean {
  return (plan.totalCount >= 3 && plan.totalCount <= 4)
    || plan.shards.length > 1;
}

export function practiceCoreSystem(system: string, capabilityCode = ''): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  return [
    system,
    '# 本轮交付策略',
    '本轮必须同时生成配套 lecture 和可立即作答的核心题目包，二者共享同一能力节点、教学目标、方法边界和难度递进。',
    'lecture 先定义本次要教会的知识与方法，questions 再围绕这些知识点设置练习；禁止生成与讲义无关的泛题，也禁止根据题目临时反推一份空洞讲义。',
    '每道题必须是独立可作答的完整单元：论证、文段、实验、数据等作答依据放入 material，prompt 只放当前设问；prompt 一旦出现“上述、以上、前述、题干、材料中、文中、该论证”等指代，material 或 materialGroupId 必须提供对应完整内容。',
    '禁止只生成“以下哪项概括上述论证”“下列哪项削弱该论证”这类缺少前置材料的空设问。没有独立材料的短题只能在 prompt 自身已包含全部作答条件时使用 material: null。',
    '每道题的 correctOptionId 和 explanation.knowledgePoint 必须随题目同时生成。knowledgePoint 只写当前题直接考查的细分考点，不提前泄露答案。',
    '本轮 explanation 只生成 knowledgePoint；详细结论、解题步骤、选项辨析和易错提醒由系统在题组发布后无感并行补全。',
    '优先保证讲义可学习，且约定题量的每道题均可展示、可选择、可判分，不要为了逐题扩写解析拖延整套内容。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

/**
 * The first provider turn publishes one coherent teaching unit: lecture plus
 * answerable questions. A minimal knowledge-point block is published with each
 * answer; detailed explanations are generated by the durable enrichment workflow.
 */
export function practiceCoreResponseSchema(
  schema: JsonObject,
  exactQuestionCount?: number,
  capabilityCode = ''
): JsonObject {
  const cloned = JSON.parse(JSON.stringify(schema)) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  const required = Array.isArray(cloned.required)
    ? cloned.required.filter((item): item is string => typeof item === 'string')
    : [];
  cloned.required = [...new Set([...required, 'lecture', 'questions'])];
  const questions = schemaRecord(properties.questions, '$.properties.questions');
  if (exactQuestionCount !== undefined) {
    const count = Math.max(1, Math.floor(exactQuestionCount));
    questions.minItems = count;
    questions.maxItems = count;
  }
  const question = schemaRecord(questions.items, '$.properties.questions.items');
  const questionProperties = schemaRecord(
    question.properties,
    '$.properties.questions.items.properties'
  );
  const questionRequired = Array.isArray(question.required)
    ? question.required.filter((item): item is string => typeof item === 'string')
    : [];
  question.required = [...new Set([
    ...questionRequired,
    'materialGroupId',
    'material',
    'explanation'
  ])];
  questionProperties.explanation = {
    type: 'object',
    additionalProperties: false,
    required: ['knowledgePoint'],
    properties: {
      knowledgePoint: { type: 'string', minLength: 2 }
    }
  };
  if (!capabilityCode.startsWith('aptitude.data_analysis.')) {
    const materialGroups = schemaRecord(properties.materialGroups, '$.properties.materialGroups');
    const materialGroup = schemaRecord(materialGroups.items, '$.properties.materialGroups.items');
    const materialGroupProperties = schemaRecord(
      materialGroup.properties,
      '$.properties.materialGroups.items.properties'
    );
    delete materialGroupProperties.table;
    delete materialGroupProperties.chart;
    delete materialGroupProperties.visual;
  }
  return cloned as JsonObject;
}

export function practiceQuestionShardSystem(
  system: string,
  capabilityCode = ''
): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  const latencyContract = questionShardLatencyContract(capabilityCode);
  return [
    system,
    '# 配套题目分片',
    '本轮只生成 questions 和必要的 materialGroups，不重新生成 lecture。',
    '用户消息中的 teachingContract 是本套题唯一的教学契约，必须围绕其中的知识、方法、边界和难度生成本分片题目。',
    '不得改变教学目标，不得输出与 teachingContract 无关的泛题。',
    '每道题必须提供可立即作答的材料、题干、选项、正确答案和 knowledgePoint；详细解析由后续无感补全。',
    latencyContract,
    'batch.existingQuestionSummaries 是其他分片已占用的设问方向，只用于去重，不得照抄。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

export function practiceQuestionShardResponseSchema(
  schema: JsonObject,
  exactQuestionCount: number,
  capabilityCode = ''
): JsonObject {
  const cloned = practiceCoreResponseSchema(schema, exactQuestionCount, capabilityCode) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  delete properties.lecture;
  cloned.required = (Array.isArray(cloned.required) ? cloned.required : [])
    .filter((item) => item !== 'lecture');
  applyQuestionShardLatencyBounds(properties, capabilityCode);
  return cloned as JsonObject;
}

export function practiceLectureSystem(system: string, capabilityCode = ''): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  return [
    system,
    '# 配套讲义分片',
    '本轮只生成 lecture。它与并行生成的题目分片共享同一个 teachingContract，必须覆盖其中的核心知识、方法边界、常见误区和迁移方向。',
    '讲义要服务于本套题的学习目标，内容清晰、可直接学习，不要生成与题目方向无关的泛泛介绍。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

export function practiceLectureResponseSchema(schema: JsonObject): JsonObject {
  const cloned = JSON.parse(JSON.stringify(schema)) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  cloned.required = ['lecture'];
  delete properties.materialGroups;
  delete properties.questions;
  return cloned as JsonObject;
}

function schemaRecord(value: unknown, path: string): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`Structured generation schema is invalid at ${path}`);
  }
  return value as Record<string, unknown>;
}

function capabilityStructuralContract(capabilityCode: string): string {
  if (capabilityCode.startsWith('aptitude.data_analysis.')) {
    return [
      '本次是资料分析题。使用一个完整 materialGroups 公共资料承载数据表或统计材料，至少两道小题引用同一个 materialGroupId。',
      '表格资料写入 materialGroups.table：columns 按展示顺序定义列，rows 按相同顺序填写单元格。柱状图、折线图、饼图、堆叠图、组合图和散点图写入 materialGroups.chart，由应用按原始数据统一绘制。',
      '只有无法用 table 或 chart 表达的特殊示意图才写入 materialGroups.visual，并提供完整 SVG 与 viewBox。materialGroups.markdown 只保存标题、资料说明和来源注记，不重复结构化块已承载的数据。',
      'chart.categories 与每组 series.values 数量必须一致；组合图通过 renderAs 指定 bar 或 line；散点图使用 points。无法结构化时才使用完整标准 GFM Markdown 表格兜底。',
      '题干只保留当前小题的设问，选项只保留当前小题的候选答案，不要把资料表重复写入各题。'
    ].join('\n');
  }
  if (isGraphicalGenerationCapability(capabilityCode)) {
    return [
      '本次是图形推理题。每道题必须提供一个完整、可独立渲染的 SVG visual，并包含 viewBox。',
      '图形顺序必须与规律顺序一致，使用 preserveAspectRatio 或等价的等比布局，不得拉伸、裁断或依赖横向滚动。',
      '若选项是图形，分别放入 option.visual；不要用文字、代码片段或拆散的多个 SVG 代替图形选项。'
    ].join('\n');
  }
  return '';
}

function isComplexVisualStructure(capabilityCode: string): boolean {
  return capabilityCode.startsWith('aptitude.data_analysis.')
    || isGraphicalGenerationCapability(capabilityCode);
}

function questionShardLatencyContract(capabilityCode: string): string {
  if (capabilityCode.startsWith('aptitude.data_analysis.')) {
    return '首轮只交付作答核心块。公共资料集中放入一个 materialGroup，题目不得重复资料；每个小题设问与选项保持简洁。';
  }
  if (isGraphicalGenerationCapability(capabilityCode)) {
    return '首轮只交付作答核心块。SVG 仅保留表达规律所需的图元和属性，不添加装饰、注释、元数据或重复图层。';
  }
  if (capabilityCode.startsWith('aptitude.verbal.')) {
    return '首轮只交付作答核心块。独立材料控制在 420 个字符内，设问控制在 100 个字符内，每个选项控制在 100 个字符内，考点名称控制在 40 个字符内。';
  }
  return '首轮只交付作答核心块。独立材料控制在 280 个字符内，设问控制在 80 个字符内，每个选项控制在 80 个字符内，考点名称控制在 40 个字符内；不得输出详细解析。';
}

function applyQuestionShardLatencyBounds(
  rootProperties: Record<string, unknown>,
  capabilityCode: string
): void {
  const questions = schemaRecord(rootProperties.questions, '$.properties.questions');
  const question = schemaRecord(questions.items, '$.properties.questions.items');
  const questionProperties = schemaRecord(
    question.properties,
    '$.properties.questions.items.properties'
  );
  const verbal = capabilityCode.startsWith('aptitude.verbal.');
  const complex = isComplexVisualStructure(capabilityCode);
  if (!complex) {
    Object.assign(schemaRecord(questionProperties.material, '$.questions.items.material'), {
      maxLength: verbal ? 420 : 280
    });
  }
  Object.assign(schemaRecord(questionProperties.prompt, '$.questions.items.prompt'), {
    maxLength: verbal ? 100 : 80
  });
  const options = schemaRecord(questionProperties.options, '$.questions.items.options');
  const option = schemaRecord(options.items, '$.questions.items.options.items');
  const optionProperties = schemaRecord(option.properties, '$.questions.items.options.items.properties');
  Object.assign(schemaRecord(optionProperties.text, '$.questions.items.options.items.text'), {
    maxLength: verbal ? 100 : 80
  });
  const explanation = schemaRecord(questionProperties.explanation, '$.questions.items.explanation');
  const explanationProperties = schemaRecord(
    explanation.properties,
    '$.questions.items.explanation.properties'
  );
  Object.assign(
    schemaRecord(explanationProperties.knowledgePoint, '$.questions.items.explanation.knowledgePoint'),
    { maxLength: 40 }
  );
}
