import type { JsonObject } from '@/kernel/public';

export interface PracticeGenerationShard {
  readonly index: number;
  readonly offset: number;
  readonly count: number;
}

export interface PracticeGenerationPlan {
  readonly totalCount: number;
  readonly shardConcurrency: number;
  readonly shards: readonly PracticeGenerationShard[];
}

const LARGE_BATCH_THRESHOLD = 12;
const DEFAULT_SHARD_SIZE = 5;
const COMPLEX_SHARD_SIZE = 4;
// Large batches use short independent provider calls. This is separate from
// the user's Agent task concurrency and remains bounded by the global gate.
const DEFAULT_SHARD_CONCURRENCY = 6;
const COMPLEX_SHARD_CONCURRENCY = 4;

export function coreGenerationTokenBudget(questionCount: number, capabilityCode = ''): number {
  const base = Math.max(4_000, 2_800 + Math.max(1, questionCount) * 750);
  const structuralAllowance = isComplexVisualStructure(capabilityCode) ? 1_600 : 0;
  return Math.min(9_000, base + structuralAllowance);
}

export function lectureGenerationTokenBudget(capabilityCode = ''): number {
  return isComplexVisualStructure(capabilityCode) ? 4_200 : 3_600;
}

export function questionShardTokenBudget(questionCount: number, capabilityCode = ''): number {
  const base = 1_400 + Math.max(1, questionCount) * 500;
  const structuralAllowance = isComplexVisualStructure(capabilityCode) ? 1_400 : 0;
  return Math.min(6_000, Math.max(2_800, base + structuralAllowance));
}

export function createPracticeGenerationPlan(
  questionCount: number,
  capabilityCode = ''
): PracticeGenerationPlan {
  const totalCount = Math.max(1, Math.floor(questionCount));
  if (totalCount <= LARGE_BATCH_THRESHOLD) {
    return {
      totalCount,
      shardConcurrency: 1,
      shards: [{ index: 0, offset: 0, count: totalCount }]
    };
  }
  const complex = isComplexVisualStructure(capabilityCode);
  const shardSize = complex ? COMPLEX_SHARD_SIZE : DEFAULT_SHARD_SIZE;
  const shards: PracticeGenerationShard[] = [];
  for (let offset = 0, index = 0; offset < totalCount; offset += shardSize, index += 1) {
    shards.push({
      index,
      offset,
      count: Math.min(shardSize, totalCount - offset)
    });
  }
  return {
    totalCount,
    shardConcurrency: complex ? COMPLEX_SHARD_CONCURRENCY : DEFAULT_SHARD_CONCURRENCY,
    shards
  };
}

export function practiceCoreSystem(system: string, capabilityCode = ''): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  return [
    system,
    '# 本轮交付策略',
    '本轮必须同时生成配套 lecture 和可立即作答的核心题目包，二者共享同一能力节点、教学目标、方法边界和难度递进。',
    'lecture 先定义本次要教会的知识与方法，questions 再围绕这些知识点设置练习；禁止生成与讲义无关的泛题，也禁止根据题目临时反推一份空洞讲义。',
    '每道题必须是独立可作答的完整单元：论证、文段、实验、数据等作答依据放入 material，prompt 只放当前设问；prompt 一旦出现“上述、以上、前述、题干、材料中、文中、该论证”等指代，material 或 materialGroupId 必须提供对应完整内容。',
    '禁止只生成“以下哪项概括上述论证”“下列哪项削弱该论证”这类缺少前置材料的空设问。没有独立材料的短题只能在 prompt 自身已包含全部作答条件时使用 material: null。',
    '每道题的 correctOptionId 和 explanation.knowledgePoint 必须随题目同时生成。knowledgePoint 只写当前题直接考查的细分考点，不提前泄露答案。',
    '本轮 explanation 只生成 knowledgePoint；详细结论、解题步骤、选项辨析和易错提醒由系统在题组发布后无感并行补全。',
    '优先保证讲义可学习，且约定题量的每道题均可展示、可选择、可判分，不要为了逐题扩写解析拖延整套内容。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

/**
 * The first provider turn publishes one coherent teaching unit: lecture plus
 * answerable questions. A minimal knowledge-point block is published with each
 * answer; detailed explanations are generated by the durable enrichment workflow.
 */
export function practiceCoreResponseSchema(
  schema: JsonObject,
  exactQuestionCount?: number
): JsonObject {
  const cloned = JSON.parse(JSON.stringify(schema)) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  const required = Array.isArray(cloned.required)
    ? cloned.required.filter((item): item is string => typeof item === 'string')
    : [];
  cloned.required = [...new Set([...required, 'lecture', 'questions'])];
  const questions = schemaRecord(properties.questions, '$.properties.questions');
  if (exactQuestionCount !== undefined) {
    const count = Math.max(1, Math.floor(exactQuestionCount));
    questions.minItems = count;
    questions.maxItems = count;
  }
  const question = schemaRecord(questions.items, '$.properties.questions.items');
  const questionProperties = schemaRecord(
    question.properties,
    '$.properties.questions.items.properties'
  );
  const questionRequired = Array.isArray(question.required)
    ? question.required.filter((item): item is string => typeof item === 'string')
    : [];
  question.required = [...new Set([
    ...questionRequired,
    'materialGroupId',
    'material',
    'explanation'
  ])];
  questionProperties.explanation = {
    type: 'object',
    additionalProperties: false,
    required: ['knowledgePoint'],
    properties: {
      knowledgePoint: { type: 'string', minLength: 2 }
    }
  };
  return cloned as JsonObject;
}

export function practiceQuestionShardSystem(
  system: string,
  capabilityCode = ''
): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  return [
    system,
    '# 配套题目分片',
    '本轮只生成 questions 和必要的 materialGroups，不重新生成 lecture。',
    '用户消息中的 teachingContract 是本套题唯一的教学契约，必须围绕其中的知识、方法、边界和难度生成本分片题目。',
    '不得改变教学目标，不得输出与 teachingContract 无关的泛题。',
    '每道题必须提供可立即作答的材料、题干、选项、正确答案和 knowledgePoint；详细解析由后续无感补全。',
    'batch.existingQuestionSummaries 是其他分片已占用的设问方向，只用于去重，不得照抄。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

export function practiceQuestionShardResponseSchema(
  schema: JsonObject,
  exactQuestionCount: number
): JsonObject {
  const cloned = practiceCoreResponseSchema(schema, exactQuestionCount) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  delete properties.lecture;
  cloned.required = (Array.isArray(cloned.required) ? cloned.required : [])
    .filter((item) => item !== 'lecture');
  return cloned as JsonObject;
}

export function practiceLectureSystem(system: string, capabilityCode = ''): string {
  const structuralContract = capabilityStructuralContract(capabilityCode);
  return [
    system,
    '# 配套讲义分片',
    '本轮只生成 lecture。它与并行生成的题目分片共享同一个 teachingContract，必须覆盖其中的核心知识、方法边界、常见误区和迁移方向。',
    '讲义要服务于本套题的学习目标，内容清晰、可直接学习，不要生成与题目方向无关的泛泛介绍。',
    ...(structuralContract ? ['# 当前题型必要结构', structuralContract] : [])
  ].join('\n\n');
}

export function practiceLectureResponseSchema(schema: JsonObject): JsonObject {
  const cloned = JSON.parse(JSON.stringify(schema)) as Record<string, unknown>;
  const properties = schemaRecord(cloned.properties, '$.properties');
  cloned.required = ['lecture'];
  delete properties.materialGroups;
  delete properties.questions;
  return cloned as JsonObject;
}

function schemaRecord(value: unknown, path: string): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`Structured generation schema is invalid at ${path}`);
  }
  return value as Record<string, unknown>;
}

function capabilityStructuralContract(capabilityCode: string): string {
  if (capabilityCode.startsWith('aptitude.data_analysis.')) {
    return [
      '本次是资料分析题。使用一个完整 materialGroups 公共资料承载数据表或统计材料，至少两道小题引用同一个 materialGroupId。',
      '公共资料中的表格使用标准 GFM Markdown，表头、分隔行和数据行必须完整；每道小题的 material 必须为 null。',
      '题干只保留当前小题的设问，选项只保留当前小题的候选答案，不要把资料表重复写入各题。'
    ].join('\n');
  }
  if (capabilityCode.startsWith('aptitude.judgment.graphical.')) {
    return [
      '本次是图形推理题。每道题必须提供一个完整、可独立渲染的 SVG visual，并包含 viewBox。',
      '图形顺序必须与规律顺序一致，使用 preserveAspectRatio 或等价的等比布局，不得拉伸、裁断或依赖横向滚动。',
      '若选项是图形，分别放入 option.visual；不要用文字、代码片段或拆散的多个 SVG 代替图形选项。'
    ].join('\n');
  }
  return '';
}

function isComplexVisualStructure(capabilityCode: string): boolean {
  return capabilityCode.startsWith('aptitude.data_analysis.')
    || capabilityCode.startsWith('aptitude.judgment.graphical.');
}
